theme: minima
title: Taha Naveed
author: Taha
email: tahaaakmal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an undergraduate student studying computer science from Comsats University Islamabad, Lahore Campus.
  I am an IBM certified Cyber Security Analyst, Microsoft Innovative Educator, Junior Data Analyst, Web Developer
  and want to be a GitHub Campus Expert for my campus.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  TahaNaveed # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

